config/routes.rb
Rails.application.routes.draw do

  get 'detail_incomes/index'

  get 'trees/index'

  get 'resource_activities/index'

  get 'resource_activities_trees/index'

  get 'show_reports/index'

  devise_for :users, :controllers => {:registrations => "authentication/registrations"}
  devise_scope :user do
    get "/users" => "authentication/registrations#index", as: "show_users_registration"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'

  resources  :zones, :activities, :trees, :collections, :detail_incomes, :administration, :resource_activities, :resource_activities_trees

  resources  :members, :charges, :general_meetings, :meetings, :meeting_members, :diaries, :contacts, :activity_contacts

  resources :income_summary, controller: "reports/income_summary"

  resources :resources_reforestation, controller: "reports/resources_reforestation"

  resources :adquisition_tree, controller: "reports/adquisition_tree"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new # guest user (not logged in)
    if user.administrator_rol?
      can :manage, :all
    end
    if user.executive_role?
      can :manage, User
    end
    if user.subexecutive_role?
      can :manage, User
    end
    if user.user_role?
      can :manage, User
    end

  end
end

app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to  :zone
    has_many :collections
    has_many :resource_activity
    has_many :general_meetings
    has_many :activity_contacts
end

def campos_utiles
   "Código: #{id}, Tipo: #{tipo}, Fecha:#{fecha_inicio}, Zona:#{zone.nombre}"
 end

app/models/activity_contact.rb
class ActivityContact < ApplicationRecord
  belongs_to  :contact
  belongs_to  :activity
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
  has_many    :members
end

app/models/collection.rb
class Collection < ApplicationRecord
    belongs_to :activity
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :activity_contacts
end

app/models/detail_income.rb
class DetailIncome < ApplicationRecord
	belongs_to  :tree
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :meeting
end

app/models/general_meeting.rb
class GeneralMeeting < ApplicationRecord
    belongs_to  :activity
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to  :activity
  has_many :diaries
end

app/models/meeting_member.rb
class MeetingMember < ApplicationRecord
  belongs_to  :meeting
  belongs_to  :member
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to  :charge
  has_many    :general_meetings
  has_many    :meetings
end

def nombre_completo
   "#{primer_nombre} #{segundo_nombre} #{primer_apellido} #{segundo_apellido}"
 end

app/models/resource.rb
class Resource < ApplicationRecord
end

app/models/resource_activity.rb
class ResourceActivity < ApplicationRecord
	belongs_to  :activity
    has_many :resource_activities_tree
end

app/models/tree.rb
class Tree < ApplicationRecord
	has_many :detail_income 
	has_many :resource_activities_tree
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/zone.rb
class Zone < ApplicationRecord
    has_many    :activities
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    #GET /charges
    def index
        @charges = Charge.all.order('id DESC')
    end

    #GET /charges/new
    def new
        @charge = Charge.new
    end

    #POST /charges
    def create
        @charge = Charge.new(charge_params);
        if @charge.save
            flash[:notice] = "Cargo creado con éxito."
            redirect_to :action => 'index'
        else
            render :new
        end
    end

    # GET /charges/:id/edit
    def edit
        @charge = Charge.find(params[:id])
    end

    # PUT /charges
    def update
        charge = Charge.find(params[:charge][:id])
        charge.update_attributes(charge_params)
        flash[:notice] = "El cargo ha sido editado con éxito."
        redirect_to :action => 'index'
    end

    # DELETE /charges
    def destroy
        charge = Charge.find(params[:id])
        #if Charge.where(charge_id: charge).empty?
            charge.destroy
            flash[:notice] = "Cargo eliminado con éxito."
            redirect_to :action => 'index'
        #else
        #    flash[:notice] = "el miembro a eliminar tiene elementos asociados."
        #    redirect_to :action => 'index'
        #end
    end

    private
    def charge_params
      params.require(:charge).permit(:nombre, :descripcion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/charges/edit.html.erb
<div class="ui raised very padded text container segment">
    <%= link_to "Atras", :back %>
    <h2 class="ui header">Editar Cargo</h2>
    <div class="ui form">
        <%= form_for(@charge) do |f| %>

        <%= f.hidden_field :id %>

        <div class="field">
            <%= f.label :nombre %><br />
            <%= f.text_field :nombre %>
        </div>

        <div class="field">
            <%= f.label :descripcion %><br />
            <%= f.text_area :descripcion %>
        </div>

        <div class="actions">
            <%= f.submit "Guardar", class: "ui primary button" %>
        </div>

        <% end %>
    </div>
</div>

<%= javascript_include_tag "validate/charge" %>

app/views/charges/index.html.erb
<div class="ui container">

    <%= link_to "Nuevo cargo", new_charge_path, class: "ui primary button" %>

    <table class="ui fixed table ">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>

            <% @charges.each do |charge| %>

                  <tr>
                    <td><%= charge.id %></td>
                    <td><%= charge.nombre %></td>
                    <td><%= charge.descripcion %></td>
                    <td>
                        <%= link_to raw('<div class="ui mini circular icon button" data-tooltip="Editar" data-inverted="" data-position="right left" data-offset="50">
<i class="large edit icon"></i></div>'), edit_charge_path(charge) %>
                        <%= link_to raw('<div class="ui mini circular icon button" data-tooltip="Eliminar" data-inverted="" data-position="right left">
<i class="large erase icon"></i></div>'), charge_path(charge), method: :delete %>
                    </td>
                </tr>

            <% end %>

        </tbody>
    </table>
<%= link_to "Atras", :controller=>"dashboard", :action=>"index" %>

</div>

app/views/charges/new.html.erb
<div class="ui raised very padded text container segment">
    <%= link_to "Atras", :back %>
    <h2 class="ui header">Nuevo Cargo</h2>
    <div class="ui form">
        <%= form_for(@charge) do |f| %>

        <div class="field">
            <%= f.label :nombre %><br />
            <%= f.text_field :nombre %>
        </div>

        <div class="field">
            <%= f.label :descripcion %><br />
            <%= f.text_area :descripcion %>
        </div>

        <div class="actions">
            <%= f.submit "Guardar", class: "ui primary button" %>
        </div>

        <% end %>
    </div>
</div>

<%= javascript_include_tag "validate/charge" %>